services:
  db:
    image: percona/percona-server:8.4
    environment:
      MYSQL_USER: journal_cms
      MYSQL_PASSWORD: journal_cms
      MYSQL_DATABASE: journal_cms
      MYSQL_RANDOM_ROOT_PASSWORD: true
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    restart: always
    volumes:
      - redis_data:/data

  localstack:
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=${DEBUG:-0}
    volumes:
      - "localstack_data:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  app:
    build:
      context: .
      target: journal-cms
    ports:
      - 8080:80
    env_file: .env
    environment:
      DRUPAL_DATABASE_NAME: journal_cms
      DRUPAL_DATABASE_USERNAME: journal_cms
      DRUPAL_DATABASE_PASSWORD: journal_cms
      DRUPAL_DATABASE_HOST: db
      DRUPAL_DATABASE_PORT: 3306
      REDIS_HOST: redis
      JCMS_SQS_ENDPOINT: http://localstack:4566
      JCMS_SQS_REGION: us-east-1
      JCMS_SQS_QUEUE: journal-cms--dev
      AWS_ACCESS_KEY_ID: 112233445566
      AWS_SECRET_ACCESS_KEY: 112233445566
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - sites_files:/opt/drupal/web/sites/default/files/

volumes:
  db_data: {}
  redis_data: {}
  sites_files: {}
  private: {}
  localstack_data: {}
