<?php
/**
 * @file
 * JCMS migrate module file.
 */

use Drupal\Core\Database\Database;
use Drupal\Core\Database\Query\AlterableInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\migrate\Plugin\MigrateSourceInterface;
use Drupal\migrate\Plugin\MigrationInterface;
use Drupal\migrate\Row;

/**
 * Implements hook_query_TAG_alter().
 */
function jcms_migrate_query_random_alter(AlterableInterface $query) {
  $query->orderRandom();
}

/**
 * Implements hook_node_presave().
 */
function jcms_migrate_node_presave(EntityInterface $entity) {
  // If uid is not set then assign a uid of 1.
  if (empty($entity->get('uid')->getString())) {
    $entity->set('uid', 1);
  }
}

/**
 * Implements hook_migrate_prepare_row().
 */
function jcms_migrate_migrate_prepare_row(Row $row, MigrateSourceInterface $source, MigrationInterface $migration) {
  // If user source id is not recognised then set to NULL.
  if ($migration->id() != 'jcms_users_db' && $row->getSourceProperty('uid') && !in_array($row->getSourceProperty('uid'), _jcms_migrate_user_sourceids())) {
    $row->setSourceProperty('uid', NULL);
  }
}

/**
 * Get source ids of migrated users.
 *
 * @return array
 */
function _jcms_migrate_user_sourceids() {
  static $sourceids = [];

  if (empty($sourceids)) {
    $query = Database::getConnection()->select('migrate_map_jcms_users_db', 'mm_users');
    $query->addField('mm_users', 'sourceid1', 'source_id');
    if ($results = $query->execute()->fetchAllKeyed()) {
      $sourceids = array_keys($results);
    }
  }

  return $sourceids;
}
