<?php

/**
 * @file
 * Contains jcms_digest.module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\jcms_digest\Entity\Digest;
use Drupal\node\Entity\Node;
use Drupal\node\NodeInterface;

/**
 * Implements hook_node_presave().
 */
function jcms_digest_node_presave(NodeInterface $node) {
  if ($node->bundle() !== 'digest') {
    return NULL;
  }
  $node_presave = \Drupal::service('jcms_digest.hooks.node_presave');

  $admin_ui = _jcms_admin_static_store('node_digest_form_admin_ui');

  $id = $node->get('field_digest_id')->getString();

  $digest = FALSE;
  $forceAddJson = FALSE;

  // Detect if a sample digest has been generated.
  if (!preg_match('/^[0-9]{5,}$/', $id)) {
    $id = _jcms_article_entity_title_unique($node, 'digest');
    $node->set('title', 'Digest ' . $id);
    $node->set('field_digest_id', [
      'value' => $id,
    ]);
    $digest = new Digest($id, '');
    $digest->generateSampleJson();
    $forceAddJson = TRUE;
  }

  // Only update the Json field in admin UI if the node is new.
  if ($forceAddJson || (!empty($admin_ui) && $node->isNew())) {
    if (!($digest instanceof Digest)) {
      $digest = $node_presave->getDigestById($id);
    }
    $node->set('field_digest_json', [
      [
        'value' => $digest->getJson(),
      ],
    ]);
  }

  if (empty($admin_ui) || $node->isNew()) {
    if (!($digest instanceof Digest)) {
      $digest = $node_presave->getDigestById($id);
    }
    $node_presave->setPublishedStatus($node, $digest);
    $node_presave->setPublishedDate($node, $digest);
    $node_presave->setUpdatedDate($node, $digest);
    $node_presave->setSubjectTerms($node, $digest);
  }

  if (!$node->isNew()) {
    // Trigger save of nodes that reference this digest.
    $query = Drupal::entityQuery('node')
      ->condition('status', NodeInterface::PUBLISHED)
      ->condition('type', 'collection');
    $collection_ids = (clone $query)->condition('field_collection_related_content', $node->id())->execute();
    $collection_ids = array_unique(array_merge((clone $query)->condition('field_collection_related_content', $node->id())->execute(), $collection_ids));
    if ($collections = Node::loadMultiple($collection_ids)) {
      foreach ($collections as $collection) {
        $collection->set('changed', strtotime('now'));
        $collection->save();
      }
    }
  }
}

/**
 * Implements hook_form_alter().
 */
function jcms_digest_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  _jcms_admin_protect_id_field($form, $form_id);
  switch ($form_id) {
    case 'node_digest_form':
    case 'node_digest_edit_form':
      foreach (array_keys($form['actions']) as $action) {
        if ($action !== 'preview' && isset($form['actions'][$action]['#type']) && $form['actions'][$action]['#type'] === 'submit') {
          array_unshift($form['actions'][$action]['#submit'], '_jcms_article_form_node_digest_edit_form_submit');
        }
      }
      break;
  }
}

/**
 * Submit function for node_article_form and node_article_edit_form.
 */
function _jcms_article_form_node_digest_edit_form_submit($form, FormStateInterface $form_state) {
  _jcms_admin_static_store('node_digest_form_admin_ui', 1);
}
