<?php

/**
 * @file
 * Contains jcms_notifications.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_help().
 */
function jcms_notifications_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the jcms_notifications module.
    case 'help.page.jcms_notifications':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Integrates with Amazon SQS and Amazon SNS.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_entity_insert().
 */
function jcms_notifications_entity_insert(EntityInterface $entity) {
  $notification_service = \Drupal::service('jcms_notifications.notification_storage');
  $notification_service->saveNotificationEntityId($entity);
}

/**
 * Implements hook_entity_update().
 */
function jcms_notifications_entity_update(EntityInterface $entity) {
  $notification_service = \Drupal::service('jcms_notifications.notification_storage');
  $notification_service->saveNotificationEntityId($entity);
}

/**
 * Implements hook_entity_delete().
 */
function jcms_notifications_entity_delete(EntityInterface $entity) {
  $notification_service = \Drupal::service('jcms_notifications.notification_storage');
  $notification_service->saveNotificationEntityId($entity);
}
